// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgkcapukhwglqqerkneq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJna2NhcHVraHdnbHFxZXJrbmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5Njc1NzcsImV4cCI6MjA2NjU0MzU3N30.9q1Jwgsl_pcAM0Qqhy5mX0MsKUGWgcGvGzjSduou__0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);